// Copyright (c) 2021 The Houyi Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: dynamic_sampling.proto

package api_v1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Type int32

const (
	Type_CONST         Type = 0
	Type_PROBABILITY   Type = 1
	Type_RATE_LIMITING Type = 2
	Type_ADAPTIVE      Type = 3
	Type_DYNAMIC       Type = 4
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "CONST",
		1: "PROBABILITY",
		2: "RATE_LIMITING",
		3: "ADAPTIVE",
		4: "DYNAMIC",
	}
	Type_value = map[string]int32{
		"CONST":         0,
		"PROBABILITY":   1,
		"RATE_LIMITING": 2,
		"ADAPTIVE":      3,
		"DYNAMIC":       4,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_dynamic_sampling_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_dynamic_sampling_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_dynamic_sampling_proto_rawDescGZIP(), []int{0}
}

type StrategyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service    string                       `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Operations []*StrategyRequest_Operation `protobuf:"bytes,3,rep,name=operations,proto3" json:"operations,omitempty"`
}

func (x *StrategyRequest) Reset() {
	*x = StrategyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_sampling_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StrategyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyRequest) ProtoMessage() {}

func (x *StrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_sampling_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyRequest.ProtoReflect.Descriptor instead.
func (*StrategyRequest) Descriptor() ([]byte, []int) {
	return file_dynamic_sampling_proto_rawDescGZIP(), []int{0}
}

func (x *StrategyRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *StrategyRequest) GetOperations() []*StrategyRequest_Operation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type ConstSampling struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AlwaysSample bool `protobuf:"varint,1,opt,name=alwaysSample,proto3" json:"alwaysSample,omitempty"`
}

func (x *ConstSampling) Reset() {
	*x = ConstSampling{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_sampling_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConstSampling) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConstSampling) ProtoMessage() {}

func (x *ConstSampling) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_sampling_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConstSampling.ProtoReflect.Descriptor instead.
func (*ConstSampling) Descriptor() ([]byte, []int) {
	return file_dynamic_sampling_proto_rawDescGZIP(), []int{1}
}

func (x *ConstSampling) GetAlwaysSample() bool {
	if x != nil {
		return x.AlwaysSample
	}
	return false
}

type ProbabilitySampling struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SamplingRate float64 `protobuf:"fixed64,1,opt,name=samplingRate,proto3" json:"samplingRate,omitempty"`
}

func (x *ProbabilitySampling) Reset() {
	*x = ProbabilitySampling{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_sampling_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProbabilitySampling) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbabilitySampling) ProtoMessage() {}

func (x *ProbabilitySampling) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_sampling_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbabilitySampling.ProtoReflect.Descriptor instead.
func (*ProbabilitySampling) Descriptor() ([]byte, []int) {
	return file_dynamic_sampling_proto_rawDescGZIP(), []int{2}
}

func (x *ProbabilitySampling) GetSamplingRate() float64 {
	if x != nil {
		return x.SamplingRate
	}
	return 0
}

type RateLimitingSampling struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxTracesPerSecond int64 `protobuf:"varint,1,opt,name=maxTracesPerSecond,proto3" json:"maxTracesPerSecond,omitempty"`
}

func (x *RateLimitingSampling) Reset() {
	*x = RateLimitingSampling{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_sampling_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RateLimitingSampling) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitingSampling) ProtoMessage() {}

func (x *RateLimitingSampling) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_sampling_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitingSampling.ProtoReflect.Descriptor instead.
func (*RateLimitingSampling) Descriptor() ([]byte, []int) {
	return file_dynamic_sampling_proto_rawDescGZIP(), []int{3}
}

func (x *RateLimitingSampling) GetMaxTracesPerSecond() int64 {
	if x != nil {
		return x.MaxTracesPerSecond
	}
	return 0
}

type AdaptiveSampling struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SamplingRate float64 `protobuf:"fixed64,1,opt,name=samplingRate,proto3" json:"samplingRate,omitempty"`
}

func (x *AdaptiveSampling) Reset() {
	*x = AdaptiveSampling{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_sampling_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdaptiveSampling) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdaptiveSampling) ProtoMessage() {}

func (x *AdaptiveSampling) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_sampling_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdaptiveSampling.ProtoReflect.Descriptor instead.
func (*AdaptiveSampling) Descriptor() ([]byte, []int) {
	return file_dynamic_sampling_proto_rawDescGZIP(), []int{4}
}

func (x *AdaptiveSampling) GetSamplingRate() float64 {
	if x != nil {
		return x.SamplingRate
	}
	return 0
}

type DynamicSampling struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SamplingRate float64 `protobuf:"fixed64,1,opt,name=samplingRate,proto3" json:"samplingRate,omitempty"`
}

func (x *DynamicSampling) Reset() {
	*x = DynamicSampling{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_sampling_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DynamicSampling) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicSampling) ProtoMessage() {}

func (x *DynamicSampling) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_sampling_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicSampling.ProtoReflect.Descriptor instead.
func (*DynamicSampling) Descriptor() ([]byte, []int) {
	return file_dynamic_sampling_proto_rawDescGZIP(), []int{5}
}

func (x *DynamicSampling) GetSamplingRate() float64 {
	if x != nil {
		return x.SamplingRate
	}
	return 0
}

type PerOperationStrategy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service   string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Operation string `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Type      Type   `protobuf:"varint,3,opt,name=type,proto3,enum=sampling.Type" json:"type,omitempty"`
	// Types that are assignable to Strategy:
	//	*PerOperationStrategy_Const
	//	*PerOperationStrategy_Probability
	//	*PerOperationStrategy_RateLimiting
	//	*PerOperationStrategy_Adaptive
	//	*PerOperationStrategy_Dynamic
	Strategy isPerOperationStrategy_Strategy `protobuf_oneof:"strategy"`
}

func (x *PerOperationStrategy) Reset() {
	*x = PerOperationStrategy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_sampling_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PerOperationStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerOperationStrategy) ProtoMessage() {}

func (x *PerOperationStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_sampling_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerOperationStrategy.ProtoReflect.Descriptor instead.
func (*PerOperationStrategy) Descriptor() ([]byte, []int) {
	return file_dynamic_sampling_proto_rawDescGZIP(), []int{6}
}

func (x *PerOperationStrategy) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *PerOperationStrategy) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *PerOperationStrategy) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_CONST
}

func (m *PerOperationStrategy) GetStrategy() isPerOperationStrategy_Strategy {
	if m != nil {
		return m.Strategy
	}
	return nil
}

func (x *PerOperationStrategy) GetConst() *ConstSampling {
	if x, ok := x.GetStrategy().(*PerOperationStrategy_Const); ok {
		return x.Const
	}
	return nil
}

func (x *PerOperationStrategy) GetProbability() *ProbabilitySampling {
	if x, ok := x.GetStrategy().(*PerOperationStrategy_Probability); ok {
		return x.Probability
	}
	return nil
}

func (x *PerOperationStrategy) GetRateLimiting() *RateLimitingSampling {
	if x, ok := x.GetStrategy().(*PerOperationStrategy_RateLimiting); ok {
		return x.RateLimiting
	}
	return nil
}

func (x *PerOperationStrategy) GetAdaptive() *AdaptiveSampling {
	if x, ok := x.GetStrategy().(*PerOperationStrategy_Adaptive); ok {
		return x.Adaptive
	}
	return nil
}

func (x *PerOperationStrategy) GetDynamic() *DynamicSampling {
	if x, ok := x.GetStrategy().(*PerOperationStrategy_Dynamic); ok {
		return x.Dynamic
	}
	return nil
}

type isPerOperationStrategy_Strategy interface {
	isPerOperationStrategy_Strategy()
}

type PerOperationStrategy_Const struct {
	Const *ConstSampling `protobuf:"bytes,4,opt,name=const,proto3,oneof"`
}

type PerOperationStrategy_Probability struct {
	Probability *ProbabilitySampling `protobuf:"bytes,5,opt,name=probability,proto3,oneof"`
}

type PerOperationStrategy_RateLimiting struct {
	RateLimiting *RateLimitingSampling `protobuf:"bytes,6,opt,name=rateLimiting,proto3,oneof"`
}

type PerOperationStrategy_Adaptive struct {
	Adaptive *AdaptiveSampling `protobuf:"bytes,7,opt,name=adaptive,proto3,oneof"`
}

type PerOperationStrategy_Dynamic struct {
	Dynamic *DynamicSampling `protobuf:"bytes,8,opt,name=dynamic,proto3,oneof"`
}

func (*PerOperationStrategy_Const) isPerOperationStrategy_Strategy() {}

func (*PerOperationStrategy_Probability) isPerOperationStrategy_Strategy() {}

func (*PerOperationStrategy_RateLimiting) isPerOperationStrategy_Strategy() {}

func (*PerOperationStrategy_Adaptive) isPerOperationStrategy_Strategy() {}

func (*PerOperationStrategy_Dynamic) isPerOperationStrategy_Strategy() {}

type StrategiesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Strategies []*PerOperationStrategy `protobuf:"bytes,1,rep,name=strategies,proto3" json:"strategies,omitempty"`
}

func (x *StrategiesResponse) Reset() {
	*x = StrategiesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_sampling_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StrategiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategiesResponse) ProtoMessage() {}

func (x *StrategiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_sampling_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategiesResponse.ProtoReflect.Descriptor instead.
func (*StrategiesResponse) Descriptor() ([]byte, []int) {
	return file_dynamic_sampling_proto_rawDescGZIP(), []int{7}
}

func (x *StrategiesResponse) GetStrategies() []*PerOperationStrategy {
	if x != nil {
		return x.Strategies
	}
	return nil
}

type NullRely struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NullRely) Reset() {
	*x = NullRely{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_sampling_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullRely) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullRely) ProtoMessage() {}

func (x *NullRely) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_sampling_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullRely.ProtoReflect.Descriptor instead.
func (*NullRely) Descriptor() ([]byte, []int) {
	return file_dynamic_sampling_proto_rawDescGZIP(), []int{8}
}

type UpdateTagsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tags []*EvaluatingTag `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *UpdateTagsRequest) Reset() {
	*x = UpdateTagsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_sampling_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagsRequest) ProtoMessage() {}

func (x *UpdateTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_sampling_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagsRequest.ProtoReflect.Descriptor instead.
func (*UpdateTagsRequest) Descriptor() ([]byte, []int) {
	return file_dynamic_sampling_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTagsRequest) GetTags() []*EvaluatingTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type StrategyRequest_Operation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Qps  float64 `protobuf:"fixed64,2,opt,name=qps,proto3" json:"qps,omitempty"`
}

func (x *StrategyRequest_Operation) Reset() {
	*x = StrategyRequest_Operation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_sampling_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StrategyRequest_Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyRequest_Operation) ProtoMessage() {}

func (x *StrategyRequest_Operation) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_sampling_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyRequest_Operation.ProtoReflect.Descriptor instead.
func (*StrategyRequest_Operation) Descriptor() ([]byte, []int) {
	return file_dynamic_sampling_proto_rawDescGZIP(), []int{0, 0}
}

func (x *StrategyRequest_Operation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StrategyRequest_Operation) GetQps() float64 {
	if x != nil {
		return x.Qps
	}
	return 0
}

var File_dynamic_sampling_proto protoreflect.FileDescriptor

var file_dynamic_sampling_proto_rawDesc = []byte{
	0x0a, 0x16, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x5f, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x69,
	0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x69,
	0x6e, 0x67, 0x1a, 0x0b, 0x68, 0x6f, 0x75, 0x79, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xa3, 0x01, 0x0a, 0x0f, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a,
	0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x23, 0x2e, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x74, 0x72,
	0x61, 0x74, 0x65, 0x67, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x1a, 0x31, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x71, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x03, 0x71, 0x70, 0x73, 0x22, 0x33, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x53, 0x61,
	0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x6c, 0x77, 0x61, 0x79, 0x73,
	0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x61, 0x6c,
	0x77, 0x61, 0x79, 0x73, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x22, 0x39, 0x0a, 0x13, 0x50, 0x72,
	0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e,
	0x67, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67, 0x52, 0x61, 0x74,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e,
	0x67, 0x52, 0x61, 0x74, 0x65, 0x22, 0x46, 0x0a, 0x14, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67, 0x12, 0x2e, 0x0a,
	0x12, 0x6d, 0x61, 0x78, 0x54, 0x72, 0x61, 0x63, 0x65, 0x73, 0x50, 0x65, 0x72, 0x53, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x6d, 0x61, 0x78, 0x54, 0x72,
	0x61, 0x63, 0x65, 0x73, 0x50, 0x65, 0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x22, 0x36, 0x0a,
	0x10, 0x41, 0x64, 0x61, 0x70, 0x74, 0x69, 0x76, 0x65, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e,
	0x67, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67, 0x52, 0x61, 0x74,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e,
	0x67, 0x52, 0x61, 0x74, 0x65, 0x22, 0x35, 0x0a, 0x0f, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63,
	0x53, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x61, 0x6d, 0x70,
	0x6c, 0x69, 0x6e, 0x67, 0x52, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c,
	0x73, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67, 0x52, 0x61, 0x74, 0x65, 0x22, 0xa9, 0x03, 0x0a,
	0x14, 0x50, 0x65, 0x72, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72,
	0x61, 0x74, 0x65, 0x67, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x73, 0x61,
	0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x2f, 0x0a, 0x05, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x6f, 0x6e, 0x73,
	0x74, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x05, 0x63, 0x6f, 0x6e,
	0x73, 0x74, 0x12, 0x41, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x69,
	0x6e, 0x67, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x53, 0x61,
	0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x62, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x44, 0x0a, 0x0c, 0x72, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x61,
	0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74,
	0x69, 0x6e, 0x67, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x0c, 0x72,
	0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x38, 0x0a, 0x08, 0x61,
	0x64, 0x61, 0x70, 0x74, 0x69, 0x76, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x73, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x41, 0x64, 0x61, 0x70, 0x74, 0x69, 0x76,
	0x65, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x08, 0x61, 0x64, 0x61,
	0x70, 0x74, 0x69, 0x76, 0x65, 0x12, 0x35, 0x0a, 0x07, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e,
	0x67, 0x2e, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e,
	0x67, 0x48, 0x00, 0x52, 0x07, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x42, 0x0a, 0x0a, 0x08,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x22, 0x54, 0x0a, 0x12, 0x53, 0x74, 0x72, 0x61,
	0x74, 0x65, 0x67, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e,
	0x0a, 0x0a, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x50, 0x65,
	0x72, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65,
	0x67, 0x79, 0x52, 0x0a, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x69, 0x65, 0x73, 0x22, 0x0a,
	0x0a, 0x08, 0x4e, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x6c, 0x79, 0x22, 0x3d, 0x0a, 0x11, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x28, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x68, 0x6f, 0x75, 0x79, 0x69, 0x2e, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x54, 0x61, 0x67, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x2a, 0x50, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x4f, 0x4e, 0x53, 0x54, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b,
	0x50, 0x52, 0x4f, 0x42, 0x41, 0x42, 0x49, 0x4c, 0x49, 0x54, 0x59, 0x10, 0x01, 0x12, 0x11, 0x0a,
	0x0d, 0x52, 0x41, 0x54, 0x45, 0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x02,
	0x12, 0x0c, 0x0a, 0x08, 0x41, 0x44, 0x41, 0x50, 0x54, 0x49, 0x56, 0x45, 0x10, 0x03, 0x12, 0x0b,
	0x0a, 0x07, 0x44, 0x59, 0x4e, 0x41, 0x4d, 0x49, 0x43, 0x10, 0x04, 0x32, 0x8e, 0x01, 0x0a, 0x0f,
	0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12,
	0x48, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x69, 0x65, 0x73,
	0x12, 0x19, 0x2e, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x74, 0x72, 0x61,
	0x74, 0x65, 0x67, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x61,
	0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x69, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x07, 0x50, 0x72, 0x6f,
	0x6d, 0x6f, 0x74, 0x65, 0x12, 0x10, 0x2e, 0x68, 0x6f, 0x75, 0x79, 0x69, 0x2e, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x12, 0x2e, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e,
	0x67, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x6c, 0x79, 0x22, 0x00, 0x32, 0x53, 0x0a, 0x10,
	0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x6f, 0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x12, 0x3f, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x67, 0x73, 0x12, 0x1b,
	0x2e, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x73, 0x61,
	0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x6c, 0x79, 0x22,
	0x00, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x68, 0x6f, 0x75, 0x79, 0x69, 0x2d, 0x74, 0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x2f, 0x68, 0x6f,
	0x75, 0x79, 0x69, 0x2f, 0x69, 0x64, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x5f, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dynamic_sampling_proto_rawDescOnce sync.Once
	file_dynamic_sampling_proto_rawDescData = file_dynamic_sampling_proto_rawDesc
)

func file_dynamic_sampling_proto_rawDescGZIP() []byte {
	file_dynamic_sampling_proto_rawDescOnce.Do(func() {
		file_dynamic_sampling_proto_rawDescData = protoimpl.X.CompressGZIP(file_dynamic_sampling_proto_rawDescData)
	})
	return file_dynamic_sampling_proto_rawDescData
}

var file_dynamic_sampling_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dynamic_sampling_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_dynamic_sampling_proto_goTypes = []interface{}{
	(Type)(0),                         // 0: sampling.Type
	(*StrategyRequest)(nil),           // 1: sampling.StrategyRequest
	(*ConstSampling)(nil),             // 2: sampling.ConstSampling
	(*ProbabilitySampling)(nil),       // 3: sampling.ProbabilitySampling
	(*RateLimitingSampling)(nil),      // 4: sampling.RateLimitingSampling
	(*AdaptiveSampling)(nil),          // 5: sampling.AdaptiveSampling
	(*DynamicSampling)(nil),           // 6: sampling.DynamicSampling
	(*PerOperationStrategy)(nil),      // 7: sampling.PerOperationStrategy
	(*StrategiesResponse)(nil),        // 8: sampling.StrategiesResponse
	(*NullRely)(nil),                  // 9: sampling.NullRely
	(*UpdateTagsRequest)(nil),         // 10: sampling.UpdateTagsRequest
	(*StrategyRequest_Operation)(nil), // 11: sampling.StrategyRequest.Operation
	(*EvaluatingTag)(nil),             // 12: houyi.EvaluatingTag
	(*Operation)(nil),                 // 13: houyi.Operation
}
var file_dynamic_sampling_proto_depIdxs = []int32{
	11, // 0: sampling.StrategyRequest.operations:type_name -> sampling.StrategyRequest.Operation
	0,  // 1: sampling.PerOperationStrategy.type:type_name -> sampling.Type
	2,  // 2: sampling.PerOperationStrategy.const:type_name -> sampling.ConstSampling
	3,  // 3: sampling.PerOperationStrategy.probability:type_name -> sampling.ProbabilitySampling
	4,  // 4: sampling.PerOperationStrategy.rateLimiting:type_name -> sampling.RateLimitingSampling
	5,  // 5: sampling.PerOperationStrategy.adaptive:type_name -> sampling.AdaptiveSampling
	6,  // 6: sampling.PerOperationStrategy.dynamic:type_name -> sampling.DynamicSampling
	7,  // 7: sampling.StrategiesResponse.strategies:type_name -> sampling.PerOperationStrategy
	12, // 8: sampling.UpdateTagsRequest.tags:type_name -> houyi.EvaluatingTag
	1,  // 9: sampling.strategyManager.GetStrategies:input_type -> sampling.StrategyRequest
	13, // 10: sampling.strategyManager.Promote:input_type -> houyi.Operation
	10, // 11: sampling.EvaluatorManager.UpdateTags:input_type -> sampling.UpdateTagsRequest
	8,  // 12: sampling.strategyManager.GetStrategies:output_type -> sampling.StrategiesResponse
	9,  // 13: sampling.strategyManager.Promote:output_type -> sampling.NullRely
	9,  // 14: sampling.EvaluatorManager.UpdateTags:output_type -> sampling.NullRely
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_dynamic_sampling_proto_init() }
func file_dynamic_sampling_proto_init() {
	if File_dynamic_sampling_proto != nil {
		return
	}
	file_houyi_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_dynamic_sampling_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StrategyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamic_sampling_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConstSampling); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamic_sampling_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProbabilitySampling); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamic_sampling_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RateLimitingSampling); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamic_sampling_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdaptiveSampling); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamic_sampling_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DynamicSampling); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamic_sampling_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PerOperationStrategy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamic_sampling_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StrategiesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamic_sampling_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullRely); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamic_sampling_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTagsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamic_sampling_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StrategyRequest_Operation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_dynamic_sampling_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*PerOperationStrategy_Const)(nil),
		(*PerOperationStrategy_Probability)(nil),
		(*PerOperationStrategy_RateLimiting)(nil),
		(*PerOperationStrategy_Adaptive)(nil),
		(*PerOperationStrategy_Dynamic)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dynamic_sampling_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_dynamic_sampling_proto_goTypes,
		DependencyIndexes: file_dynamic_sampling_proto_depIdxs,
		EnumInfos:         file_dynamic_sampling_proto_enumTypes,
		MessageInfos:      file_dynamic_sampling_proto_msgTypes,
	}.Build()
	File_dynamic_sampling_proto = out.File
	file_dynamic_sampling_proto_rawDesc = nil
	file_dynamic_sampling_proto_goTypes = nil
	file_dynamic_sampling_proto_depIdxs = nil
}
