// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// StrategyManagerClient is the client API for StrategyManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StrategyManagerClient interface {
	GetStrategy(ctx context.Context, in *StrategyRequest, opts ...grpc.CallOption) (*StrategyResponse, error)
}

type strategyManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewStrategyManagerClient(cc grpc.ClientConnInterface) StrategyManagerClient {
	return &strategyManagerClient{cc}
}

func (c *strategyManagerClient) GetStrategy(ctx context.Context, in *StrategyRequest, opts ...grpc.CallOption) (*StrategyResponse, error) {
	out := new(StrategyResponse)
	err := c.cc.Invoke(ctx, "/sampling.StrategyManager/GetStrategy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StrategyManagerServer is the server API for StrategyManager service.
// All implementations must embed UnimplementedStrategyManagerServer
// for forward compatibility
type StrategyManagerServer interface {
	GetStrategy(context.Context, *StrategyRequest) (*StrategyResponse, error)
	mustEmbedUnimplementedStrategyManagerServer()
}

// UnimplementedStrategyManagerServer must be embedded to have forward compatible implementations.
type UnimplementedStrategyManagerServer struct {
}

func (UnimplementedStrategyManagerServer) GetStrategy(context.Context, *StrategyRequest) (*StrategyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStrategy not implemented")
}
func (UnimplementedStrategyManagerServer) mustEmbedUnimplementedStrategyManagerServer() {}

// UnsafeStrategyManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StrategyManagerServer will
// result in compilation errors.
type UnsafeStrategyManagerServer interface {
	mustEmbedUnimplementedStrategyManagerServer()
}

func RegisterStrategyManagerServer(s grpc.ServiceRegistrar, srv StrategyManagerServer) {
	s.RegisterService(&_StrategyManager_serviceDesc, srv)
}

func _StrategyManager_GetStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyManagerServer).GetStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sampling.StrategyManager/GetStrategy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyManagerServer).GetStrategy(ctx, req.(*StrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StrategyManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sampling.StrategyManager",
	HandlerType: (*StrategyManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStrategy",
			Handler:    _StrategyManager_GetStrategy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dynamic_sampling.proto",
}

// DynamicStrategyManagerClient is the client API for DynamicStrategyManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DynamicStrategyManagerClient interface {
	Promote(ctx context.Context, in *Operation, opts ...grpc.CallOption) (*NullRely, error)
}

type dynamicStrategyManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewDynamicStrategyManagerClient(cc grpc.ClientConnInterface) DynamicStrategyManagerClient {
	return &dynamicStrategyManagerClient{cc}
}

func (c *dynamicStrategyManagerClient) Promote(ctx context.Context, in *Operation, opts ...grpc.CallOption) (*NullRely, error) {
	out := new(NullRely)
	err := c.cc.Invoke(ctx, "/sampling.DynamicStrategyManager/Promote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DynamicStrategyManagerServer is the server API for DynamicStrategyManager service.
// All implementations must embed UnimplementedDynamicStrategyManagerServer
// for forward compatibility
type DynamicStrategyManagerServer interface {
	Promote(context.Context, *Operation) (*NullRely, error)
	mustEmbedUnimplementedDynamicStrategyManagerServer()
}

// UnimplementedDynamicStrategyManagerServer must be embedded to have forward compatible implementations.
type UnimplementedDynamicStrategyManagerServer struct {
}

func (UnimplementedDynamicStrategyManagerServer) Promote(context.Context, *Operation) (*NullRely, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Promote not implemented")
}
func (UnimplementedDynamicStrategyManagerServer) mustEmbedUnimplementedDynamicStrategyManagerServer() {
}

// UnsafeDynamicStrategyManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DynamicStrategyManagerServer will
// result in compilation errors.
type UnsafeDynamicStrategyManagerServer interface {
	mustEmbedUnimplementedDynamicStrategyManagerServer()
}

func RegisterDynamicStrategyManagerServer(s grpc.ServiceRegistrar, srv DynamicStrategyManagerServer) {
	s.RegisterService(&_DynamicStrategyManager_serviceDesc, srv)
}

func _DynamicStrategyManager_Promote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Operation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicStrategyManagerServer).Promote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sampling.DynamicStrategyManager/Promote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicStrategyManagerServer).Promote(ctx, req.(*Operation))
	}
	return interceptor(ctx, in, info, handler)
}

var _DynamicStrategyManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sampling.DynamicStrategyManager",
	HandlerType: (*DynamicStrategyManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Promote",
			Handler:    _DynamicStrategyManager_Promote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dynamic_sampling.proto",
}

// EvaluatorManagerClient is the client API for EvaluatorManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EvaluatorManagerClient interface {
	GetTags(ctx context.Context, in *GetTagsRequest, opts ...grpc.CallOption) (*GetTagsRely, error)
	UpdateTags(ctx context.Context, in *UpdateTagsRequest, opts ...grpc.CallOption) (*UpdateTagsReply, error)
}

type evaluatorManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewEvaluatorManagerClient(cc grpc.ClientConnInterface) EvaluatorManagerClient {
	return &evaluatorManagerClient{cc}
}

func (c *evaluatorManagerClient) GetTags(ctx context.Context, in *GetTagsRequest, opts ...grpc.CallOption) (*GetTagsRely, error) {
	out := new(GetTagsRely)
	err := c.cc.Invoke(ctx, "/sampling.EvaluatorManager/GetTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *evaluatorManagerClient) UpdateTags(ctx context.Context, in *UpdateTagsRequest, opts ...grpc.CallOption) (*UpdateTagsReply, error) {
	out := new(UpdateTagsReply)
	err := c.cc.Invoke(ctx, "/sampling.EvaluatorManager/UpdateTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EvaluatorManagerServer is the server API for EvaluatorManager service.
// All implementations must embed UnimplementedEvaluatorManagerServer
// for forward compatibility
type EvaluatorManagerServer interface {
	GetTags(context.Context, *GetTagsRequest) (*GetTagsRely, error)
	UpdateTags(context.Context, *UpdateTagsRequest) (*UpdateTagsReply, error)
	mustEmbedUnimplementedEvaluatorManagerServer()
}

// UnimplementedEvaluatorManagerServer must be embedded to have forward compatible implementations.
type UnimplementedEvaluatorManagerServer struct {
}

func (UnimplementedEvaluatorManagerServer) GetTags(context.Context, *GetTagsRequest) (*GetTagsRely, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTags not implemented")
}
func (UnimplementedEvaluatorManagerServer) UpdateTags(context.Context, *UpdateTagsRequest) (*UpdateTagsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTags not implemented")
}
func (UnimplementedEvaluatorManagerServer) mustEmbedUnimplementedEvaluatorManagerServer() {}

// UnsafeEvaluatorManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EvaluatorManagerServer will
// result in compilation errors.
type UnsafeEvaluatorManagerServer interface {
	mustEmbedUnimplementedEvaluatorManagerServer()
}

func RegisterEvaluatorManagerServer(s grpc.ServiceRegistrar, srv EvaluatorManagerServer) {
	s.RegisterService(&_EvaluatorManager_serviceDesc, srv)
}

func _EvaluatorManager_GetTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvaluatorManagerServer).GetTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sampling.EvaluatorManager/GetTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvaluatorManagerServer).GetTags(ctx, req.(*GetTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EvaluatorManager_UpdateTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvaluatorManagerServer).UpdateTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sampling.EvaluatorManager/UpdateTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvaluatorManagerServer).UpdateTags(ctx, req.(*UpdateTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EvaluatorManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sampling.EvaluatorManager",
	HandlerType: (*EvaluatorManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTags",
			Handler:    _EvaluatorManager_GetTags_Handler,
		},
		{
			MethodName: "UpdateTags",
			Handler:    _EvaluatorManager_UpdateTags_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dynamic_sampling.proto",
}
