// Copyright (c) 2021 The Houyi Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: houyi.proto

package api_v1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type EvaluatingTag_ValueType int32

const (
	EvaluatingTag_INTEGER EvaluatingTag_ValueType = 0
	EvaluatingTag_FLOAT   EvaluatingTag_ValueType = 1
	EvaluatingTag_BOOLEAN EvaluatingTag_ValueType = 2
	EvaluatingTag_STRING  EvaluatingTag_ValueType = 4
)

// Enum value maps for EvaluatingTag_ValueType.
var (
	EvaluatingTag_ValueType_name = map[int32]string{
		0: "INTEGER",
		1: "FLOAT",
		2: "BOOLEAN",
		4: "STRING",
	}
	EvaluatingTag_ValueType_value = map[string]int32{
		"INTEGER": 0,
		"FLOAT":   1,
		"BOOLEAN": 2,
		"STRING":  4,
	}
)

func (x EvaluatingTag_ValueType) Enum() *EvaluatingTag_ValueType {
	p := new(EvaluatingTag_ValueType)
	*p = x
	return p
}

func (x EvaluatingTag_ValueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EvaluatingTag_ValueType) Descriptor() protoreflect.EnumDescriptor {
	return file_houyi_proto_enumTypes[0].Descriptor()
}

func (EvaluatingTag_ValueType) Type() protoreflect.EnumType {
	return &file_houyi_proto_enumTypes[0]
}

func (x EvaluatingTag_ValueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EvaluatingTag_ValueType.Descriptor instead.
func (EvaluatingTag_ValueType) EnumDescriptor() ([]byte, []int) {
	return file_houyi_proto_rawDescGZIP(), []int{2, 0}
}

type EvaluatingTag_OperationType int32

const (
	EvaluatingTag_EQUAL_TO                 EvaluatingTag_OperationType = 0
	EvaluatingTag_NOT_EQUAL_TO             EvaluatingTag_OperationType = 1
	EvaluatingTag_GREATER_THAN             EvaluatingTag_OperationType = 2
	EvaluatingTag_GREATER_THAN_OR_EQUAL_TO EvaluatingTag_OperationType = 3
	EvaluatingTag_LESS_THAN                EvaluatingTag_OperationType = 4
	EvaluatingTag_LESS_THAN_OR_EQUAL_TO    EvaluatingTag_OperationType = 5
)

// Enum value maps for EvaluatingTag_OperationType.
var (
	EvaluatingTag_OperationType_name = map[int32]string{
		0: "EQUAL_TO",
		1: "NOT_EQUAL_TO",
		2: "GREATER_THAN",
		3: "GREATER_THAN_OR_EQUAL_TO",
		4: "LESS_THAN",
		5: "LESS_THAN_OR_EQUAL_TO",
	}
	EvaluatingTag_OperationType_value = map[string]int32{
		"EQUAL_TO":                 0,
		"NOT_EQUAL_TO":             1,
		"GREATER_THAN":             2,
		"GREATER_THAN_OR_EQUAL_TO": 3,
		"LESS_THAN":                4,
		"LESS_THAN_OR_EQUAL_TO":    5,
	}
)

func (x EvaluatingTag_OperationType) Enum() *EvaluatingTag_OperationType {
	p := new(EvaluatingTag_OperationType)
	*p = x
	return p
}

func (x EvaluatingTag_OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EvaluatingTag_OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_houyi_proto_enumTypes[1].Descriptor()
}

func (EvaluatingTag_OperationType) Type() protoreflect.EnumType {
	return &file_houyi_proto_enumTypes[1]
}

func (x EvaluatingTag_OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EvaluatingTag_OperationType.Descriptor instead.
func (EvaluatingTag_OperationType) EnumDescriptor() ([]byte, []int) {
	return file_houyi_proto_rawDescGZIP(), []int{2, 1}
}

type Operation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service   string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Operation string `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
}

func (x *Operation) Reset() {
	*x = Operation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_houyi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_houyi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_houyi_proto_rawDescGZIP(), []int{0}
}

func (x *Operation) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Operation) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

type Relation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From *Operation `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To   *Operation `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *Relation) Reset() {
	*x = Relation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_houyi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Relation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relation) ProtoMessage() {}

func (x *Relation) ProtoReflect() protoreflect.Message {
	mi := &file_houyi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relation.ProtoReflect.Descriptor instead.
func (*Relation) Descriptor() ([]byte, []int) {
	return file_houyi_proto_rawDescGZIP(), []int{1}
}

func (x *Relation) GetFrom() *Operation {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Relation) GetTo() *Operation {
	if x != nil {
		return x.To
	}
	return nil
}

type EvaluatingTag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TagName       string                      `protobuf:"bytes,1,opt,name=tagName,proto3" json:"tagName,omitempty"`
	OperationType EvaluatingTag_OperationType `protobuf:"varint,2,opt,name=operationType,proto3,enum=houyi.EvaluatingTag_OperationType" json:"operationType,omitempty"`
	ValueType     EvaluatingTag_ValueType     `protobuf:"varint,3,opt,name=valueType,proto3,enum=houyi.EvaluatingTag_ValueType" json:"valueType,omitempty"`
	// Types that are assignable to Value:
	//	*EvaluatingTag_IntegerVal
	//	*EvaluatingTag_FloatVal
	//	*EvaluatingTag_BooleanVal
	//	*EvaluatingTag_StringVal
	Value isEvaluatingTag_Value `protobuf_oneof:"value"`
}

func (x *EvaluatingTag) Reset() {
	*x = EvaluatingTag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_houyi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvaluatingTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluatingTag) ProtoMessage() {}

func (x *EvaluatingTag) ProtoReflect() protoreflect.Message {
	mi := &file_houyi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluatingTag.ProtoReflect.Descriptor instead.
func (*EvaluatingTag) Descriptor() ([]byte, []int) {
	return file_houyi_proto_rawDescGZIP(), []int{2}
}

func (x *EvaluatingTag) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

func (x *EvaluatingTag) GetOperationType() EvaluatingTag_OperationType {
	if x != nil {
		return x.OperationType
	}
	return EvaluatingTag_EQUAL_TO
}

func (x *EvaluatingTag) GetValueType() EvaluatingTag_ValueType {
	if x != nil {
		return x.ValueType
	}
	return EvaluatingTag_INTEGER
}

func (m *EvaluatingTag) GetValue() isEvaluatingTag_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *EvaluatingTag) GetIntegerVal() int64 {
	if x, ok := x.GetValue().(*EvaluatingTag_IntegerVal); ok {
		return x.IntegerVal
	}
	return 0
}

func (x *EvaluatingTag) GetFloatVal() float64 {
	if x, ok := x.GetValue().(*EvaluatingTag_FloatVal); ok {
		return x.FloatVal
	}
	return 0
}

func (x *EvaluatingTag) GetBooleanVal() bool {
	if x, ok := x.GetValue().(*EvaluatingTag_BooleanVal); ok {
		return x.BooleanVal
	}
	return false
}

func (x *EvaluatingTag) GetStringVal() string {
	if x, ok := x.GetValue().(*EvaluatingTag_StringVal); ok {
		return x.StringVal
	}
	return ""
}

type isEvaluatingTag_Value interface {
	isEvaluatingTag_Value()
}

type EvaluatingTag_IntegerVal struct {
	IntegerVal int64 `protobuf:"varint,4,opt,name=integerVal,proto3,oneof"`
}

type EvaluatingTag_FloatVal struct {
	FloatVal float64 `protobuf:"fixed64,5,opt,name=floatVal,proto3,oneof"`
}

type EvaluatingTag_BooleanVal struct {
	BooleanVal bool `protobuf:"varint,6,opt,name=booleanVal,proto3,oneof"`
}

type EvaluatingTag_StringVal struct {
	StringVal string `protobuf:"bytes,7,opt,name=stringVal,proto3,oneof"`
}

func (*EvaluatingTag_IntegerVal) isEvaluatingTag_Value() {}

func (*EvaluatingTag_FloatVal) isEvaluatingTag_Value() {}

func (*EvaluatingTag_BooleanVal) isEvaluatingTag_Value() {}

func (*EvaluatingTag_StringVal) isEvaluatingTag_Value() {}

var File_houyi_proto protoreflect.FileDescriptor

var file_houyi_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x68, 0x6f, 0x75, 0x79, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x68,
	0x6f, 0x75, 0x79, 0x69, 0x22, 0x43, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x52, 0x0a, 0x08, 0x52, 0x65, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x68, 0x6f, 0x75, 0x79, 0x69, 0x2e, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x20, 0x0a, 0x02, 0x74,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x68, 0x6f, 0x75, 0x79, 0x69, 0x2e,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x02, 0x74, 0x6f, 0x22, 0x86, 0x04,
	0x0a, 0x0d, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x67, 0x12,
	0x18, 0x0a, 0x07, 0x74, 0x61, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x74, 0x61, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x48, 0x0a, 0x0d, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x22, 0x2e, 0x68, 0x6f, 0x75, 0x79, 0x69, 0x2e, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x54, 0x61, 0x67, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x0d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x3c, 0x0a, 0x09, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x68, 0x6f, 0x75, 0x79, 0x69, 0x2e, 0x45,
	0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x67, 0x2e, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x20, 0x0a, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x56, 0x61, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72,
	0x56, 0x61, 0x6c, 0x12, 0x1c, 0x0a, 0x08, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61, 0x6c, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x08, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61,
	0x6c, 0x12, 0x20, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x56, 0x61, 0x6c, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x0a, 0x62, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e,
	0x56, 0x61, 0x6c, 0x12, 0x1e, 0x0a, 0x09, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x56, 0x61, 0x6c, 0x22, 0x3c, 0x0a, 0x09, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x54, 0x45, 0x47, 0x45, 0x52, 0x10, 0x00, 0x12, 0x09, 0x0a,
	0x05, 0x46, 0x4c, 0x4f, 0x41, 0x54, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x42, 0x4f, 0x4f, 0x4c,
	0x45, 0x41, 0x4e, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10,
	0x04, 0x22, 0x89, 0x01, 0x0a, 0x0d, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x45, 0x51, 0x55, 0x41, 0x4c, 0x5f, 0x54, 0x4f, 0x10,
	0x00, 0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x4f, 0x54, 0x5f, 0x45, 0x51, 0x55, 0x41, 0x4c, 0x5f, 0x54,
	0x4f, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x47, 0x52, 0x45, 0x41, 0x54, 0x45, 0x52, 0x5f, 0x54,
	0x48, 0x41, 0x4e, 0x10, 0x02, 0x12, 0x1c, 0x0a, 0x18, 0x47, 0x52, 0x45, 0x41, 0x54, 0x45, 0x52,
	0x5f, 0x54, 0x48, 0x41, 0x4e, 0x5f, 0x4f, 0x52, 0x5f, 0x45, 0x51, 0x55, 0x41, 0x4c, 0x5f, 0x54,
	0x4f, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x4c, 0x45, 0x53, 0x53, 0x5f, 0x54, 0x48, 0x41, 0x4e,
	0x10, 0x04, 0x12, 0x19, 0x0a, 0x15, 0x4c, 0x45, 0x53, 0x53, 0x5f, 0x54, 0x48, 0x41, 0x4e, 0x5f,
	0x4f, 0x52, 0x5f, 0x45, 0x51, 0x55, 0x41, 0x4c, 0x5f, 0x54, 0x4f, 0x10, 0x05, 0x42, 0x07, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x6f, 0x75, 0x79, 0x69, 0x2d, 0x74, 0x72, 0x61, 0x63, 0x69,
	0x6e, 0x67, 0x2f, 0x68, 0x6f, 0x75, 0x79, 0x69, 0x2f, 0x69, 0x64, 0x6c, 0x2f, 0x61, 0x70, 0x69,
	0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_houyi_proto_rawDescOnce sync.Once
	file_houyi_proto_rawDescData = file_houyi_proto_rawDesc
)

func file_houyi_proto_rawDescGZIP() []byte {
	file_houyi_proto_rawDescOnce.Do(func() {
		file_houyi_proto_rawDescData = protoimpl.X.CompressGZIP(file_houyi_proto_rawDescData)
	})
	return file_houyi_proto_rawDescData
}

var file_houyi_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_houyi_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_houyi_proto_goTypes = []interface{}{
	(EvaluatingTag_ValueType)(0),     // 0: houyi.EvaluatingTag.ValueType
	(EvaluatingTag_OperationType)(0), // 1: houyi.EvaluatingTag.OperationType
	(*Operation)(nil),                // 2: houyi.Operation
	(*Relation)(nil),                 // 3: houyi.Relation
	(*EvaluatingTag)(nil),            // 4: houyi.EvaluatingTag
}
var file_houyi_proto_depIdxs = []int32{
	2, // 0: houyi.Relation.from:type_name -> houyi.Operation
	2, // 1: houyi.Relation.to:type_name -> houyi.Operation
	1, // 2: houyi.EvaluatingTag.operationType:type_name -> houyi.EvaluatingTag.OperationType
	0, // 3: houyi.EvaluatingTag.valueType:type_name -> houyi.EvaluatingTag.ValueType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_houyi_proto_init() }
func file_houyi_proto_init() {
	if File_houyi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_houyi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Operation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_houyi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Relation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_houyi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvaluatingTag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_houyi_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*EvaluatingTag_IntegerVal)(nil),
		(*EvaluatingTag_FloatVal)(nil),
		(*EvaluatingTag_BooleanVal)(nil),
		(*EvaluatingTag_StringVal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_houyi_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_houyi_proto_goTypes,
		DependencyIndexes: file_houyi_proto_depIdxs,
		EnumInfos:         file_houyi_proto_enumTypes,
		MessageInfos:      file_houyi_proto_msgTypes,
	}.Build()
	File_houyi_proto = out.File
	file_houyi_proto_rawDesc = nil
	file_houyi_proto_goTypes = nil
	file_houyi_proto_depIdxs = nil
}
