apiVersion: v1
kind: Service
metadata:
  name: collector
  labels:
    app: collector
    service: collector
spec:
  ports:
    - port: 14268
      name: http
    - port: 14250
      name: grpc
    - port: 14269
      name: admin
  selector:
    app: collector
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: houyi-collector
  labels:
    account: collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector-v1
  labels:
    app: collector
    version: v1
spec:
  selector:
    matchLabels:
      app: collector
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: collector
        version: v1
    spec:
      serviceAccountName: houyi-collector
      containers:
        - name: houyi-collector
          image: houyitracing/collector
          imagePullPolicy: Always
          env:
            - name: MAX_NUM_CHILD_NODES
              value: "4"
            - name: CASSANDRA_SERVERS
              value: "192.168.31.229"
            - name: LOG_LEVEL
              value: "debug"
          ports:
            - containerPort: 14250
            - containerPort: 14268
            - containerPort: 14269
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: { }
---
